### ISSUE TITLE
Add safeguards against panics

### ISSUE THREAD

**Issue by t0rr3sp3dr0** [inloco/incognia-go#28]
We should follow what we do on our Android/iOS SDKs and have handlers to prevent possible panics escaping the library and causing some problem on the customer's service.

In Java we would have a try/catch block for Throwables:
```java
try {
    // library implementation
} catch (Throwable t) {
    // record exception
}
```

We can do a similar thing in Go with the recover function:
```go
defer func() {
    if r := recover(); r != nil {
        // record exception
    }
}()

// library implementation
```

**Comment by lucasbarross** [comment]
Solved! https://github.com/inloco/incognia-go/pull/33
